name: Check Net88 Domain

on:
  schedule:
    - cron: '0 */6 * * *'  # Chạy mỗi 6 tiếng
  workflow_dispatch:      # Cho phép chạy thủ công

jobs:
  check-domain:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Check Net88 domain
      run: |
        FINAL_URL=$(curl -s -o /dev/null -w "%{url_effective}\n" -L "https://net88.com")
        echo "Final URL: $FINAL_URL"
        
        DOMAIN=$(echo $FINAL_URL | sed 's|^\(https\?://[^/]*\).*|\1|')
        echo "Domain: $DOMAIN"
        
        TIMESTAMP=$(date +%s)
        ISO_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        
        cat > latest-domain.json << EOF
        {
          "domain": "$DOMAIN",
          "updated": $TIMESTAMP,
          "checked_at": "$ISO_DATE",
          "status": "active",
          "fallback_domains": [
            "https://net88.com",
            "https://net88.net", 
            "https://net88.info"
          ],
          "notes": "Auto-updated by GitHub Actions"
        }
        EOF
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add latest-domain.json
        git diff --staged --quiet || git commit -m "Auto-update Net88 domain: $(date)"
        git push
